---
title: "gdsc correlate"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
library(reshape)
library(GEOquery)
library(gplots)
library(dplyr)
library(GSVA)
library(GSEABase)
library(org.Hs.eg.db)
library(annotate)
library(GO.db)
library(limma)
library(reshape2)
library(biomaRt)
library(data.table)

```


```{r exp input}
gdsc.expression<-fread('../data/GDSC/sanger1018_brainarray_ensemblgene_rma.txt',sep = 'auto',check.names = FALSE,header = TRUE,blank.lines.skip=TRUE)
gdsc.expression<-as.data.frame(gdsc.expression)
row.names(gdsc.expression)<-gdsc.expression$ensembl_gene
gdsc.expression$ensembl_gene<-NULL

gdsc_cl <- read.csv('../data/GDSC/Cell line details.csv')
gdsc.cl.dr <- gdsc_cl[which(gdsc_cl$Drug.Response == 'Y'),]
gdsc.cl <- as.character(gdsc.cl.dr$COSMIC.identifier)

gdsc_tissue <- read.csv('../data/GDSC/COSMIC tissue classification-Table 1.csv')
gdsc_tissue.dr <- gdsc_tissue[which(gdsc_tissue$COSMIC_ID %in% gdsc.cl),]
gdsc_tissue.dr.nohem <- gdsc_tissue.dr[which(gdsc_tissue.dr$Site != 'haematopoietic_and_lymphoid_tissue'),]

sample <- as.character(gdsc_tissue.dr.nohem$COSMIC_ID)
sample.toanalyze <- intersect(sample,colnames(gdsc.expression))

gdsc.exp <- gdsc.expression[,sample.toanalyze]
#gdsc.exp.nohemo.z <- apply(as.matrix(gdsc.exp),2,scale)
#row.names(gdsc.exp.nohemo.z)<-rownames(gdsc.exp)
#save(gdsc.exp.nohemo.z,file = '../data/GDSC/gdsc_exp_nohemo_z.Rdata')
```

```{r drug input}
gdsc.drug<-read.csv("../data/GDSC/v17.3_fitted_dose_response.csv")
gdsc.tocast<-data.frame(gdsc.drug$COSMIC_ID,gdsc.drug$DRUG_NAME,gdsc.drug$LN_IC50)
colnames(gdsc.tocast)<-c('COSMIC_ID','drug','LN_IC50')
gdsc.cast<-dcast(gdsc.tocast,formula = COSMIC_ID ~ drug,fun.aggregate = mean)
row.names(gdsc.cast)<-gdsc.cast$COSMIC_ID
gdsc.cast$COSMIC_ID<-NULL
gdsc.cast <- exp(gdsc.cast)
gdsc.cast_o<-gdsc.cast
```
```{r info}
genes <- row.names(gdsc.exp)
ensembl <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
gene_list <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id",
"entrezgene", 'hgnc_symbol',"description"),values=genes,mart= ensembl)
gene.name <- gene_list$hgnc_symbol
gene.ORF <- gene_list$entrezgene
gene.list <- gene_list$ensembl_gene_id
```

```{r corr}
#gene.name.u <- unique(gene.name)
gdsc.tocorr <- gdsc.exp
#row.names(gdsc.corr) <- gene.name.u
gdsc.corr <- gdsc.tocorr[,-which(is.na(match(colnames(gdsc.tocorr), row.names(gdsc.cast))))]
drug.corr<-gdsc.cast[match(colnames(gdsc.corr), row.names(gdsc.cast)),] 
```

```{r}
drug.corr[,'docetaxel']
```



```{r corr1}
regulator.drug.exp.cor<-apply(drug.corr,2,function(x){
  ss <- x
  result<-apply(gdsc.corr,1,function(x){return(cor.test(x,ss,method = 'spearman')$estimate)})
  return(result)
    }
  )
```

```{r}
doc.drug <- drug.corr[,'Docetaxel']
doc.exp <- gdsc.corr['ENSG00000111700',]
```

