---
title: "ccle correlation correction"
output:
  pdf_document: default
  html_notebook: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
library(reshape)
library(GEOquery)
library(gplots)
library(dplyr)
#library(heatmaply)
library(GSVA)
library(GSEABase)
library(knitr)
#library(kableExtra)
library(org.Hs.eg.db)
library(annotate)
library(data.table)
library(biomaRt)
library(GO.db)
```

```{r input}
gdsc.expression<-fread('../data/GDSC/sanger1018_brainarray_ensemblgene_rma.txt',sep = 'auto',check.names = FALSE,header = TRUE,blank.lines.skip=TRUE)
gdsc.expression<-as.data.frame(gdsc.expression)
row.names(gdsc.expression)<-gdsc.expression$ensembl_gene
gdsc.expression$ensembl_gene<-NULL
```

```{r normalize}
gene.exp.z <- apply(gdsc.expression,2,scale)
colnames(gene.exp.z) <- colnames(gdsc.expression)
row.names(gene.exp.z) <- row.names(gdsc.expression)
save(gene.exp.z,file = '../data/GDSC/geneexpression_gdsc_zscore_new.Rdata' )
#write.csv(gene.exp.nohemo.z,file = '../data/GDSC/geneexpression_zscore_new.csv')
```


```{r input2}
gdsc_cl <- read.csv('../data/GDSC/Cell line details.csv')
gdsc.cl.dr <- gdsc_cl[which(gdsc_cl$Drug.Response == 'Y'),]
gdsc.cl <- as.character(gdsc.cl.dr$COSMIC.identifier)

gdsc_tissue <- read.csv('../data/GDSC/COSMIC tissue classification-Table 1.csv')
gdsc_tissue.dr <- gdsc_tissue[which(gdsc_tissue$COSMIC_ID %in% gdsc.cl),]
gdsc_tissue.dr.nohem <- gdsc_tissue.dr[which(gdsc_tissue.dr$Site != 'haematopoietic_and_lymphoid_tissue'),]

sample <- as.character(gdsc_tissue.dr.nohem$COSMIC_ID)
sample.toanalyze <- intersect(sample,colnames(gdsc.expression))

gdsc.exp <- gdsc.expression[,sample.toanalyze]
```
# drug correlation analysis with target sets

```{r entrez info}
genes <- row.names(gdsc.exp)
ensembl <- useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
gene_list <- getBM(filters= "ensembl_gene_id", attributes= c("ensembl_gene_id",
"entrezgene",'hgnc_symbol'),values=genes,mart= ensembl)
gene.name <- gene_list$hgnc_symbol
gene.ORF <- gene_list$entrezgene
gene.list <- gene_list$ensembl_gene_id
```

```{r ssgsea,eval=FALSE}
load('../data/GDSC/geneexpression_gdsc_zscore_new.Rdata' )
regset <- getGmt('../data/Gene_regulators/targetset_nodup_entrez.gmt.txt')

gene.exp.z.gst<-gene.exp.z[match(gene.list,row.names(gene.exp.z)),]
row.names(gene.exp.z.gst) <- gene.ORF

regsva<-gsva(gene.exp.z.gst,regset,method=c('ssgsea'))
save(regsva,file ='../data/GDSC/regsva.Rdata')

```

```{r input3}
load('../data/GDSC/geneexpression_gdsc_zscore_new.Rdata' )
load('../data/GDSC/regsva.Rdata')
```

```{r drug input}
gdsc.drug<-read.csv("../data/GDSC/v17.3_fitted_dose_response.csv")
gdsc.tocast<-data.frame(gdsc.drug$COSMIC_ID,gdsc.drug$DRUG_NAME,gdsc.drug$LN_IC50)
colnames(gdsc.tocast)<-c('COSMIC_ID','drug','LN_IC50')
gdsc.cast<-dcast(gdsc.tocast,formula = COSMIC_ID ~ drug,fun.aggregate = mean)
row.names(gdsc.cast)<-gdsc.cast$COSMIC_ID
gdsc.cast$COSMIC_ID<-NULL
gdsc.cast <- exp(gdsc.cast)
gdsc.cast_o<-gdsc.cast
```

```{r drug 2}
cl.tocorre <- intersect(colnames(gdsc.exp),row.names(gdsc.cast))
exp.tocorre <- gdsc.exp[,cl.tocorre]
ssgsea.tocorre <- regsva[,cl.tocorre]
tocorre.drug <- gdsc.cast[cl.tocorre,]
```

```{r threshold}
gdsc.tocast<-data.frame(gdsc.drug$COSMIC_ID,gdsc.drug$DRUG_NAME,gdsc.drug$MAX_CONC_MICROMOLAR)
colnames(gdsc.tocast)<-c('COSMIC_ID','drug','MAX_CONC_MICROMOLAR')
gdsc.cast.max<-dcast(gdsc.tocast,formula = COSMIC_ID ~ drug,fun.aggregate = mean)
row.names(gdsc.cast.max)<-gdsc.cast.max$COSMIC_ID
gdsc.cast.max$COSMIC_ID <- NULL
```


```{r corr0}
test <- list()
#regulator.drug.ssgsea.cor<-sapply(c(1:251),function(x){
  for (i in c(1:251)){
  dr <- tocorre.drug[,i]
  names(dr) <- cl.tocorre
  cl.thres <- gdsc.cast.max[cl.tocorre,i]
  cl.sen <- cl.tocorre[dr < cl.thres]
  cl.sen <- cl.sen[! is.na(cl.sen)]
  ss <- dr[cl.sen]
  test[[i]] <- ss
  }
#  if (length(cl.sen) > 0){
  result<-apply(ssgsea.tocorre[,cl.sen],1,function(x){return(cor.test(x,ss,method = 'spearman')$estimate)})
#  else{result <- NA}
#  return(result)
#    }
#  ) # how much is the number of cl per correlation experiment
names(test) <- colnames(tocorre.drug)
test.len <- lapply(test,length)
test.len <- unlist(test.len)
barplot(test.len,names.arg = names(test.len),las = 2,cex.names = .5)
```

```{r corr}
drug.keep <-names(test.len[test.len >=20])
tocorre.drug <- tocorre.drug[,drug.keep]
gdsc.cast.max <- gdsc.cast.max[,drug.keep]
regulator.drug.ssgsea.cor<-sapply(c(1:ncol(tocorre.drug)),function(x){
  dr <- tocorre.drug[,x]
  names(dr) <- cl.tocorre
  cl.thres <- gdsc.cast.max[cl.tocorre,x]
  cl.sen <- cl.tocorre[dr < cl.thres]
  cl.sen <- cl.sen[! is.na(cl.sen)]
  ss <- dr[cl.sen]
  result<-apply(ssgsea.tocorre[,cl.sen],1,function(x){return(cor.test(x,ss,method = 'spearman')$estimate)})
  return(result)
    }
  ) 
colnames(regulator.drug.ssgsea.cor) <- colnames(tocorre.drug)
```

```{r reg class}
regulator.class<- read.delim('../data/Gene_regulators/Regulator classification.txt',row.names = 1)
druginfo<- read.csv('../data/CCLE/CCLE_NP24.2009_profiling_2012.02.20.csv',row.names = 1)
geneage<-read.csv('../data/Gene_regulators/geneIDs_entrez_final_phylostrata_phy1_phy2_phy3_no_TCGA.txt',header = TRUE,row.names = 1)
```
```{r gene}
hp.gene<-row.names(regulator.drug.ssgsea.cor)
toremove.gene <- hp.gene[which(regulator.class[hp.gene,1] %in% c('None',NA))]
regulator.drug.ssgsea.cor.sub<-subset(regulator.drug.ssgsea.cor, !hp.gene %in% toremove.gene)
```
```{r info,fig.width=12,fig.height=12}
my_palette <- colorRampPalette(c("dodgerblue3", "white", "deeppink3"))(n = 4)

hp<-heatmap.2(regulator.drug.ssgsea.cor.sub,trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette)
#pdf('../output/gdsc_drugheatmap_target.pdf',width = 12,height = 12) 
#heatmap.2(regulator.drug.ssgsea.cor.sub,trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette)
#dev.off()
new.row.name<-row.names(regulator.drug.ssgsea.cor.sub)[rev(hp$rowInd)]
new.col.name<-colnames(regulator.drug.ssgsea.cor.sub)[hp$colInd]
regulator.drug.ssgsea.cor.2<-regulator.drug.ssgsea.cor.sub[new.row.name,new.col.name]
heatmap.2(regulator.drug.ssgsea.cor.2,Rowv = FALSE, Colv = FALSE,trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette)
```

```{r class,fig.width=12,fig.height=12}
hp.class<-regulator.class[new.row.name,]
hp.class<-as.factor(hp.class)
levels(hp.class) <- c('blue','yellow','orange','red','black')
heatmap.2(regulator.drug.ssgsea.cor.2,trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette, Rowv = FALSE, Colv = FALSE,RowSideColors = as.character(hp.class))
```
```{r age,fig.width=12,fig.height=12}
hp.age <- geneage[new.row.name,2]
uc_group<-ifelse(hp.age<4,'blue','red')
heatmap.2(regulator.drug.ssgsea.cor.2,trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette,RowSideColors = uc_group,Rowv = FALSE, Colv = FALSE)
```
```{r goslim0,eval = FALSE}
slim_terms <- getOBOCollection("../data/Gene_regulators/goslim_generic.obo")
xx <- as.list(org.Hs.egGO2ALLEGS)
goids <- xx[2:3]
gonames<-Term(GOTERM)
go_bp_children <- GOBPOFFSPRING$"GO:0008150"
slim_terms <- ids(slim_terms)[which(ids(slim_terms) %in% go_bp_children)]
slim_terms <- cbind(slim_terms, unname(gonames[match(slim_terms, names(gonames))]))
pathways <- xx[slim_terms[,1]]
pathways <- pathways[!is.na(names(pathways))]
names(pathways) <- unname(gonames[match(names(pathways), names(gonames))])
gogsva<-gsva(gene.exp.z.gst,pathways,method=c('ssgsea'))
save(gogsva,file ='../data/GDSC/gogsva.Rdata')
```
```{r goslim2}
load(file ='../data/GDSC/gogsva.Rdata')
tocorre.goslim<-gogsva[,cl.tocorre]
```
```{r goslim3}
regulator.drug.goslim.cor<-sapply(c(1:ncol(tocorre.drug)),function(x){
  dr <- tocorre.drug[,x]
  names(dr) <- cl.tocorre
  cl.thres <- gdsc.cast.max[cl.tocorre,x]
  cl.sen <- cl.tocorre[dr < cl.thres]
  cl.sen <- cl.sen[! is.na(cl.sen)]
  ss <- dr[cl.sen]
  result<-apply(tocorre.goslim[,cl.sen],1,function(x){return(cor.test(x,ss,method = 'spearman')$estimate)})
  return(result)
    }
  ) 
colnames(regulator.drug.goslim.cor) <- colnames(tocorre.drug)
```
```{r goslim4,fig.width=12,fig.height=12}
my_palette <- colorRampPalette(c("dodgerblue3", "white", "deeppink3"))(n = 4)
#pdf('drugheatmap_goslim.pdf',width = 12,height = 12) 
hp.2<-heatmap.2(regulator.drug.goslim.cor,trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette)
heatmap.2(regulator.drug.goslim.cor,trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette)
#dev.off()

```

```{r go age,fig.height=12,fig.width=12}
load('../data/Gene_regulators/goslim_age.Rdata')
goslim.col <- ifelse(goslim.age == 'UC','blue','red')
goslim.col[is.na(goslim.col)]<-'white'
#pdf('~/git/myproject/output/goslim_gdsc.pdf')
heatmap.2(regulator.drug.goslim.cor,trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette,RowSideColors = goslim.col)
#dev.off()
heatmaply(regulator.drug.goslim.cor,trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette,RowSideColors = goslim.col)
```

```{r drug1}
druginfo <- read.csv('../data/GDSC/Screened_Compounds.csv')
load('../data/drug_totest.Rdata')
groupname[1] <- 'Saracatinib'
groupname[5] <- 'Palbociclib'
drug.totest.df <- druginfo[which(druginfo$Drug.Name %in% groupname),]
drug.totest.df <- drug.totest.df[c(1:4),]

```


```{r drug2}
drug.totest <- as.character(drug.totest.df$Drug.Name)
drug.totest<-drug.totest[-c(2,3)]      
heatmap.2(regulator.drug.goslim.cor[,drug.totest],trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette,RowSideColors = goslim.col)
```







