---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
library(reshape)
library(GEOquery)
library(gplots)
library(dplyr)
library(heatmaply)
library(GSVA)
library(GSEABase)
library(knitr)
library(kableExtra)
library(org.Hs.eg.db)
library(annotate)
library(cogena)
library(biomaRt)
setwd('~/git/myproject')
```

```{r}
regset <- getGmt('../data/Gene_regulators/targetset.gmt.txt')
```

```{r}
geneset<-geneIds(regset)
geneset.nodup<-unique(geneset)
targetset.name<-names(geneset)
targetset.nodup.name<-targetset.name[!duplicated(geneset)]
names(geneset.nodup)<-targetset.nodup.name
```

```{r}

```


```{r}
gmtlist2file(geneset.nodup,file = '../data/Gene_regulators/targetset_nodup.gmt.txt')
```
```{r}
regset <- getGmt('../data/Gene_regulators/targetset_nodup.gmt.txt')
```
```{r}
geneset<-geneIds(regset)

genename <- unlist(geneset[1])

#mart = useEnsembl("ENSEMBL_MART_ENSEMBL")
getEntrez <- function(x){mart=useMart(biomart="ensembl", dataset="hsapiens_gene_ensembl")
info = getBM(attributes=c('hgnc_symbol','entrezgene'),values=x,filters = "hgnc_symbol", mart = mart)
colnames(info) <- c('gene','entrez') 
return(info$entrez)}

geneset.entrez <-lapply(geneset,getEntrez)

gmtlist2file(geneset.entrez,file = '../data/Gene_regulators/targetset_nodup_entrez.gmt.txt')

```
```



