---
title: "Correlation Analysis"
output:
  html_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(htmlwidgets)
library(limma)
library(org.Hs.eg.db)
library(annotate)
library(GEOquery)
library(grid)
library(ggplot2)
library(reshape)
library(GSVA)
library(GSEABase)
library(GO.db)
library(gplots)
library(heatmaply)
library(knitr)
library(data.table)
```

```{r load data}
load('./data/selected_cl.Rdata')
load('./data/regulators_5_cl_20_tar.Rdata')
load('./data/regulator_regulation.Rdata')
```

```{r input, include=FALSE}
mutation_o<-read.delim('./data/CCLE/CCLE_DepMap_18Q1_maf_20180207 (1).txt')
mutation<-mutation_o
mutation_s<-mutation_o[which(is.na(mutation_o$ExAC_AF)),]
mutation_s<-mutation_s[which(mutation_s$isDeleterious == 'TRUE'),]
mutation_s_w<-mutation_s
mutation_s_w<-data.frame(mutation_s$Hugo_Symbol,mutation_s$Tumor_Sample_Barcode)

genelist<-as.character(unique(mutation_s_w[,1]))
rs<-function(x){
  c<-as.character(mutation_s_w[which(mutation_s_w$mutation_s.Hugo_Symbol==x),2])
  return(c)
  }
a<-lapply(genelist,rs)
names(a)<-genelist
mutatedcelllines<-a
b<-lapply(mutatedcelllines,length)
mutatedcelllines_num<-unlist(b)

regset <- getGmt('./data/Gene_regulators/targetset_nodup.gmt.txt')
reg.list<-geneIds(regset)
reg.count<-lapply(reg.list,length)
reg.count<-unlist(reg.count)
  
regulator<-names(reg.count)
target <- unique(unlist(reg.list))

reg_m<-matrix(nrow=length(regulator),ncol=length(target))
colnames(reg_m)<-target
row.names(reg_m)<-regulator


for (i in 1:nrow(reg_m)){
  x <- regulator[i]
  for (y in reg.list[[i]])
  {reg_m[x,y] <- 1}
}

reg_m[is.na(reg_m)]<-0

```

```{r cl}
ccle.expression<-fread('./data/CCLE/CCLE_Expression_Entrez_2012-09-29.gct',skip = 2, sep = '\t')
ccle.expression_o <- ccle.expression
ccle.expression <- as.data.frame(ccle.expression)
ccle.expression <- ccle.expression[,-c(1,2)]
ccle.anno <- ccle.expression_o[,c(1,2)]
toremove <- which(ccle.anno$Description == '')
ccle.anno <- ccle.anno[-toremove,]
ccle.expression<-ccle.expression[-toremove,]


sample.info<-fread('./data/CCLE/CCLE_sample_info_file_2012-10-18.txt', sep = '\t')
cl.pos<-match(colnames(ccle.expression),sample.info$`CCLE name`)
cl.info <- sample.info[cl.pos,]
cl.toremove <- which(cl.info$`Site Primary` == 'haematopoietic_and_lymphoid_tissue')

ccle.exp <- ccle.expression[,cl.tokeep]

cl.sample <- colnames(ccle.exp)
n <- length(cl.sample)
cl<-rep(0,n)

regulators.cl <- intersect(regulator, names(mutatedcelllines))

mutation_df <- sapply(regulators.cl,function(x){return( cl.sample %in% mutatedcelllines[[x]])})

row.names(mutation_df) <- cl.sample

mutation_df <- t(mutation_df)

mt.count <- rowSums(mutation_df)
```

```{r regulator expression}
regulator.tokeep <- ccle.anno[ Description %in% selected.regulator]$Description
reg.pos <- match(regulator.tokeep,ccle.anno$Description)
regulator.exp <- ccle.exp[reg.pos,]
row.names(regulator.exp) <- regulator.tokeep
```

## correlation matrix of all regulator expression 

```{r cor0, fig.height = 10, fig.width= 10,echo=FALSE,warning=FALSE,include=FALSE}
#pdf('/Users/ll/Desktop/git/myproject/docs/firstheatmap.pdf',width = 12,height = 12) 
reg.exp.cor<-cor(t(regulator.exp))
my_palette <- colorRampPalette(c("dodgerblue3", "white", "deeppink3"))(n = 4)
heatmap.2(reg.exp.cor,trace = 'none',breaks = c(-1,-0.5,0,0.5,1), col = my_palette,cexRow = 0.65,cexCol = 0.65,keysize = 0.6,main = 'regulator expression correlation')
#dev.off()
```
## spearman correlation of all regulator expression with ssgsea scores of target sets

```{r cor2,fig.height = 7, fig.width= 7,echo = FALSE,warning=FALSE}
load('./data/ccle_regsva_regulator.Rdata')
targetset.gsva <- regsva[regulator.tokeep,]

regulator.exp.ssgsea.cor<-apply(targetset.gsva,1,function(x){
  ss <- x
  result<-apply(regulator.exp,1,function(x){return(cor.test(x,ss,method = 'spearman')$estimate)})
  return(result)
    }
  )
my_palette <- colorRampPalette(c("dodgerblue3", "white", "deeppink3"))(n = 4)
#pdf('/Users/ll/Desktop/git/myproject/docs/secondheatmap.pdf',width = 12,height = 12) 

heatmap.2(regulator.exp.ssgsea.cor,Rowv = FALSE,Colv=FALSE,trace = 'none',breaks = c(-1,-0.5,0,0.5,1),col = my_palette,main = 'regulator expression \n correlation with target set ssgsea',cexRow = 0.35,cexCol = 0.35)


```
```{r load classification}
load('./data/regulator_regulation.Rdata')
reg.class <- regulator_tb$class
names(reg.class) <- regulator_tb$regulator
reg.col <- as.factor(reg.class)
reg.level <- levels(reg.col) 
reg.level
levels(reg.col) <- c('red','pink','orange','white','blue','green')
reg.col <- as.character(reg.col[regulator.tokeep])
names(reg.col) <- regulator.tokeep
```

## Spearman correlation of all regulator expression with ssgsea scores of goslim
```{r cor3,fig.height = 12, fig.width= 12,echo = FALSE,warning=FALSE}
load('./data/gosva.Rdata')
regulator.go.ssgsea.cor<-apply(regulator.exp,1,function(x){
  ss <- x
  result<-apply(gogsva,1,function(x){return(cor.test(x,ss,method = 'spearman')$estimate)})
  return(result)
    }
  )
my_palette <- colorRampPalette(c("dodgerblue3", "white", "deeppink3"))(n = 4)
#pdf('/Users/ll/Desktop/git/myproject/docs/thirdheatmap.pdf',width = 12,height = 12) 
heatmap.2(regulator.go.ssgsea.cor,trace = 'none',
          breaks = c(-1,-0.5,0,0.5,1), 
          col = my_palette,
          margins = c(10,19),
          cexRow = 0.8,
          cexCol = 0.6,
          ColSideColors=reg.col

          )
#dev.off()
```


```{r cor4,fig.height = 12, fig.width= 12,echo = FALSE,warning=FALSE}

regulator.go.target.cor<-apply(targetset.gsva,1,function(x){
  ss <- x
  result<-apply(gogsva,1,function(x){return(cor.test(x,ss,method = 'spearman')$estimate)})
  return(result)
    }
  )
my_palette <- colorRampPalette(c("dodgerblue3", "white", "deeppink3"))(n = 4)
#pdf('/Users/ll/Desktop/git/myproject/docs/thirdheatmap.pdf',width = 12,height = 12) 
heatmap.2(regulator.go.target.cor,trace = 'none',
          breaks = c(-1,-0.5,0,0.5,1), 
          col = my_palette,
          margins = c(10,19),
          cexRow = 0.8,
          cexCol = 0.6,
          ColSideColors= reg.col
          )
#dev.off()
```



